# Copyright (C) 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

version = 1

[[annotations]]
path = [
    "**/debian/**",
    "**/*.png",
    "**/*.json",
    "**/*.rviz"
]
SPDX-FileCopyrightText = "2025 Intel Corporation"
SPDX-License-Identifier = "Apache-2.0"
