image:
  repository: eclipse-mosquitto
  tag: 2.0

auth:
  mountPath: /mosquitto/secrets
  passwordFilePath: /mosquitto/secrets/pwfile

env:
  MQTT_USER: ""
  MQTT_PASSWORD: ""

service:
  name: mqtt-broker
  type: ClusterIP

podSecurityContext:
  enabled: true
  fsGroup: 1883

containerSecurityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1883
  runAsGroup: 1883

initContainerSecurityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1883
  runAsGroup: 1883
